name = "vane"
version = "1.0.0"

description = "A SQLite driver in gleam"
licences = ["MIT"]
repository = { type = "github", user = "stndrs", repo = "vane" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"
gleam_time = ">= 1.7.0 and < 2.0.0"
esqlite = ">= 0.9.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
